# Generated by Django 4.2.2 on 2023-06-14 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_mgt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='std_mgt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('grade', models.CharField(max_length=10)),
                ('registration_date', models.DateField()),
                ('registration_status', models.BooleanField(default=False)),
                ('attendance_date', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=50)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('performance', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('attendance_date', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('leave_start_date', models.DateField()),
                ('leave_end_date', models.DateField()),
                ('leave_reason', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('teaching_assignments', models.ManyToManyField(related_name='staff', to='sch_app.course_mgt')),
            ],
        ),
        migrations.AddField(
            model_name='course_mgt',
            name='management',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sch_app.std_mgt'),
        ),
        migrations.AddField(
            model_name='course_mgt',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sch_app.staff'),
        ),
    ]
